export type {
  VxMemory,
  CreateMemoryInput,
  CreateMemoriesBatchResponse,
  CreateImportInput,
  CreateImportResponse,
  CreateImportSummary,
  CounterpartyIdentity,
  AgentMemoryIdentity,
  DigitalSpaceInput,
  ImportProvider,
  MemoryKeyInfo,
  SpaceContextInput,
  QuerySpaceInput,
  QueryMemoriesInput,
  SetMemoryPublicKeyResponse,
  ContextPacketInput,
  VxKnowledgeContext,
  CreateContextInput,
  UpdateContextInput,
  MicStoreInput,
  MicInferInput,
  MicContextInput,
  QueryResponse,
  QueryEnvelope,
  ContextPacketResponse,
  HybridQueryInput,
  MultiQueryInput,
  VxClientConfig,
  ImportChatGPTInput,
  ImportAnthropicInput,
  ImportIngestResponse,
  CascadeQueryInput,
  CascadeQueryResponse,
  EntityMergeInput,
  EntityMergeResponse,
  EmergentContextListInput,
  EmergentContextInfo,
  EmergentContextListResponse,
  CreateContextFromDescriptionInput,
  ActivateContextResponse,
  SkillsFindInput,
  SkillDescriptor,
  SkillsFindResponse,
  SkillInvokeInput,
  SkillInvokeResponse,
  HealthDetailedComponent,
  HealthDetailedResponse,
} from './vx-client.js';

export type { ImportFromTextOptions } from './import.js';

export { VxApiClient, createVxClient, waitForVxApi } from './vx-client.js';

export { importFromText, importMemories } from './import.js';
